import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
} from "@react-pdf/renderer";
import { Html } from "react-pdf-html";
import { marked } from "marked";

// Register a standard font
Font.register({
  family: "Helvetica",
  fonts: [
    {
      src: "https://fonts.gstatic.com/s/helveticaneue/v70/1Ptsg8zYS_SKggPNyC0IT4ttDfA.ttf",
    }, // Regular
    {
      src: "https://fonts.gstatic.com/s/helveticaneue/v70/1Ptsg8zYS_SKggPNyC0IT4ttDfA.ttf",
      fontWeight: "bold",
    }, // Bold (using same for now as fallback)
  ],
});

const styles = StyleSheet.create({
  page: {
    flexDirection: "column",
    backgroundColor: "#FFFFFF",
    padding: 30,
    fontFamily: "Helvetica",
  },
  header: {
    marginBottom: 20,
    borderBottomWidth: 2,
    borderBottomColor: "#F97316", // Orange-500
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#1A1A1A",
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 12,
    color: "#666666",
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 30,
    right: 30,
    textAlign: "center",
    color: "#999999",
    fontSize: 10,
    borderTopWidth: 1,
    borderTopColor: "#EEEEEE",
    paddingTop: 10,
  },
});

// Styles for HTML content
const htmlStylesheet = {
  body: {
    fontSize: 12,
    lineHeight: 1.5,
    color: "#333333",
    fontFamily: "Helvetica",
  },
  h1: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 10,
    color: "#1A1A1A",
  },
  h2: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 8,
    color: "#1A1A1A",
    borderBottom: "1px solid #EEEEEE",
    paddingBottom: 4,
  },
  h3: {
    fontSize: 14,
    fontWeight: "bold",
    marginBottom: 6,
    color: "#333333",
  },
  p: {
    marginBottom: 8,
  },
  ul: {
    marginBottom: 8,
    marginLeft: 10,
  },
  ol: {
    marginBottom: 8,
    marginLeft: 10,
  },
  li: {
    marginBottom: 4,
  },
  strong: {
    fontWeight: "bold",
  },
  em: {
    fontStyle: "italic",
  },
  code: {
    fontFamily: "Courier",
    backgroundColor: "#F5F5F5",
    padding: 2,
    fontSize: 10,
  },
  pre: {
    fontFamily: "Courier",
    backgroundColor: "#F5F5F5",
    padding: 10,
    marginBottom: 10,
    fontSize: 10,
  },
};

interface ManualPDFProps {
  content: string;
  toolName?: string;
}

export const ManualPDF: React.FC<ManualPDFProps> = ({
  content,
  toolName = "Tool Manual",
}) => {
  // Convert Markdown to HTML
  const htmlContent = marked.parse(content) as string;

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>{toolName}</Text>
          <Text style={styles.subtitle}>Generated by Toolify AI</Text>
        </View>

        <View>
          <Html stylesheet={htmlStylesheet}>{htmlContent}</Html>
        </View>

        <View style={styles.footer}>
          <Text>
            Toolify - Your Intelligent Tool Assistant •{" "}
            {new Date().toLocaleDateString()}
          </Text>
        </View>
      </Page>
    </Document>
  );
};
