import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
} from "@react-pdf/renderer";

// Register a standard font
Font.register({
  family: "Helvetica",
  fonts: [
    {
      src: "https://fonts.gstatic.com/s/helveticaneue/v70/1Ptsg8zYS_SKggPNyC0IT4ttDfA.ttf",
    }, // Regular
    {
      src: "https://fonts.gstatic.com/s/helveticaneue/v70/1Ptsg8zYS_SKggPNyC0IT4ttDfA.ttf",
      fontWeight: "bold",
    }, // Bold (using same for now as fallback)
  ],
});

const styles = StyleSheet.create({
  page: {
    flexDirection: "column",
    backgroundColor: "#FFFFFF",
    padding: 30,
    fontFamily: "Helvetica",
  },
  header: {
    marginBottom: 20,
    borderBottomWidth: 2,
    borderBottomColor: "#F97316", // Orange-500
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#1A1A1A",
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 12,
    color: "#666666",
  },
  content: {
    fontSize: 12,
    lineHeight: 1.5,
    color: "#333333",
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 30,
    right: 30,
    textAlign: "center",
    color: "#999999",
    fontSize: 10,
    borderTopWidth: 1,
    borderTopColor: "#EEEEEE",
    paddingTop: 10,
  },
});

interface ManualPDFProps {
  content: string;
  toolName?: string;
}

export const ManualPDF: React.FC<ManualPDFProps> = ({
  content,
  toolName = "Tool Manual",
}) => {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>{toolName}</Text>
          <Text style={styles.subtitle}>Generated by Toolify AI</Text>
        </View>

        <View>
          <Text style={styles.content}>{content}</Text>
        </View>

        <View style={styles.footer}>
          <Text>
            Toolify - Your Intelligent Tool Assistant •{" "}
            {new Date().toLocaleDateString()}
          </Text>
        </View>
      </Page>
    </Document>
  );
};
